/**
 * Regenerates src/registry/data.ts from Chainlink's official sources:
 * - Data Feeds: https://reference-data-directory.vercel.app/ (same source the Chainlink docs use)
 * - CCIP chain selectors: https://github.com/smartcontractkit/chain-selectors
 *
 * Run: npm -w packages/cli run update-registry
 */
import { writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const RDD_BASE = "https://reference-data-directory.vercel.app";

// chain key → RDD file slug
const FEED_CHAINS: Record<string, string> = {
  "ethereum-mainnet": "feeds-mainnet.json",
  "arbitrum-mainnet": "feeds-ethereum-mainnet-arbitrum-1.json",
  "optimism-mainnet": "feeds-ethereum-mainnet-optimism-1.json",
  "base-mainnet": "feeds-ethereum-mainnet-base-1.json",
  "polygon-mainnet": "feeds-matic-mainnet.json",
  "avalanche-mainnet": "feeds-avalanche-mainnet.json",
  "bsc-mainnet": "feeds-bsc-mainnet.json",
  "scroll-mainnet": "feeds-ethereum-mainnet-scroll-1.json",
  "linea-mainnet": "feeds-ethereum-mainnet-linea-1.json",
  "ethereum-sepolia": "feeds-ethereum-testnet-sepolia.json",
  "arbitrum-sepolia": "feeds-ethereum-testnet-sepolia-arbitrum-1.json",
  "optimism-sepolia": "feeds-ethereum-testnet-sepolia-optimism-1.json",
  "base-sepolia": "feeds-ethereum-testnet-sepolia-base-1.json",
  "avalanche-fuji": "feeds-avalanche-fuji-testnet.json",
};

const SELECTORS_URL = "https://raw.githubusercontent.com/smartcontractkit/chain-selectors/main/selectors.yml";

interface RddEntry {
  proxyAddress: string | null;
  name: string;
  decimals: number | null;
  heartbeat: number | null;
  feedCategory: string;
}

async function fetchJson(url: string): Promise<unknown> {
  const response = await fetch(url);
  if (!response.ok) throw new Error(`${url}: HTTP ${response.status}`);
  return response.json();
}

async function main(): Promise<void> {
  const feeds: Record<string, { chain: string; name: string; decimals: number; heartbeat: number; category: string }> = {};

  for (const [chain, slug] of Object.entries(FEED_CHAINS)) {
    let entries: RddEntry[];
    try {
      entries = (await fetchJson(`${RDD_BASE}/${slug}`)) as RddEntry[];
    } catch (error) {
      console.warn(`skip ${chain}: ${error instanceof Error ? error.message : error}`);
      continue;
    }
    let kept = 0;
    for (const entry of entries) {
      if (!entry.proxyAddress || typeof entry.decimals !== "number") continue;
      feeds[entry.proxyAddress.toLowerCase()] = {
        chain,
        name: entry.name,
        decimals: entry.decimals,
        heartbeat: entry.heartbeat ?? 0,
        category: entry.feedCategory || "unknown",
      };
      kept++;
    }
    console.log(`${chain}: ${kept} feeds`);
  }

  // Selectors exceed 2^53 — keep them as strings, never parse as Number.
  const selectorsYaml = await (await fetch(SELECTORS_URL)).text();
  const ccipSelectors: Record<string, string> = {};
  let currentSelector: string | null = null;
  for (const line of selectorsYaml.split("\n")) {
    const selectorMatch = /^\s+selector:\s*(\d+)\s*$/.exec(line);
    if (selectorMatch) {
      currentSelector = selectorMatch[1];
      continue;
    }
    const nameMatch = /^\s+name:\s*"([^"]+)"\s*$/.exec(line);
    if (nameMatch && currentSelector) {
      ccipSelectors[currentSelector] = nameMatch[1];
      currentSelector = null;
    }
  }
  console.log(`ccip selectors: ${Object.keys(ccipSelectors).length}`);

  const generatedAt = new Date().toISOString().slice(0, 10);
  const output = `// Generated by scripts/update-registry.ts on ${generatedAt} — do not edit by hand.
// Sources: Chainlink reference data directory (feeds) + smartcontractkit/chain-selectors (CCIP).
export interface FeedInfo {
  chain: string;
  name: string;
  decimals: number;
  heartbeat: number;
  category: string;
}

export const feeds: Record<string, FeedInfo> = ${JSON.stringify(feeds, null, 1)};

// CCIP chain selector (as decimal string, values exceed 2^53) → chain name.
export const ccipSelectors: Record<string, string> = ${JSON.stringify(ccipSelectors, null, 1)};

export const registryGeneratedAt = ${JSON.stringify(generatedAt)};
`;

  const target = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../src/registry/data.ts");
  writeFileSync(target, output, "utf8");
  console.log(`wrote ${target} (${Object.keys(feeds).length} feeds)`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
